package com.sop.backend.models;

import jakarta.persistence.*;

import java.time.LocalDateTime;

/**
 * <p>
 * This abstract base class defines common fields shared by all persistent entities.
 * It provides a technical primary key {@code id} and a creation timestamp {@code createdAt}.
 * </p>
 *
 * <p>
 * The primary key ({@code id}) is generated by Hibernate using a PostgreSQL sequence.
 * Hibernate preallocates blocks of IDs in memory (based on {@code allocationSize}) to
 * reduce database round-trips for inserts, which significantly improves performance
 * for bulk operations.
 * </p>
 *
 * <p>
 * The generated identifiers are monotonically increasing, unique, and never reused.
 * Gaps in the identifier sequence may occur and are expected behavior due to preallocation.
 * </p>
 */
@MappedSuperclass
public abstract class BaseEntity {
    @Id
    @SequenceGenerator(
            name = "global_seq",
            sequenceName = "global_seq",
            allocationSize = 50
    )
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "global_seq")
    private Long id;

    @Column(nullable = false, updatable = false)
    private final LocalDateTime createdAt = LocalDateTime.now();

    public Long getId() {
        return id;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
}
